### Giới thiệu về Pytorch và tensor

In [1]:
from google.colab import drive
drive.mount('/content/drive')
%cd '/content/drive/MyDrive/ColabNotebooks/'

Mounted at /content/drive
/content/drive/MyDrive/ColabNotebooks


In [2]:
import torch

### Tensors trong Pytorch

Pytorch Tensors

Tạo một vecto gồm 3 phần tử

In [3]:
x=torch.Tensor( [5.3 , 2.1 , -3.1 ] )
print(x)

tensor([ 5.3000,  2.1000, -3.1000])


Tạo ma trận kích thước 2x2

In [4]:
A=torch.Tensor( [ [5.3,2.1] , [0.2,2.1] ] )
print(A)

tensor([[5.3000, 2.1000],
        [0.2000, 2.1000]])


Construct a random 10x2 matrix

In [5]:
A=torch.rand(10,2)
print(A)

tensor([[0.3706, 0.1568],
        [0.9220, 0.0934],
        [0.4401, 0.5739],
        [0.4095, 0.9587],
        [0.1927, 0.3658],
        [0.4749, 0.0662],
        [0.1207, 0.9193],
        [0.0069, 0.3259],
        [0.8982, 0.1202],
        [0.4575, 0.1521]])


Construct a 10x2 matrix filled with zeros

In [6]:
A=torch.zeros(10,2)
print(A)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])


Construct a 5x2 random Tensor

In [7]:
B = torch.rand(5,2,2)
print(B)

tensor([[[0.9366, 0.3920],
         [0.9126, 0.4006]],

        [[0.3223, 0.0421],
         [0.2170, 0.2052]],

        [[0.2585, 0.1266],
         [0.4562, 0.9965]],

        [[0.3376, 0.4715],
         [0.8549, 0.9691]],

        [[0.4658, 0.8245],
         [0.1788, 0.3314]]])


In [8]:
B.size()

torch.Size([5, 2, 2])

In [9]:
B.dim()

3

In [10]:
B.type()

'torch.FloatTensor'

Kích thước và chiều của tensor

A 3-dimensional Tensor

In [11]:
A=torch.rand(3,2,2)
print(A)

tensor([[[0.4727, 0.6167],
         [0.5882, 0.9241]],

        [[0.3213, 0.4224],
         [0.8634, 0.0226]],

        [[0.9752, 0.1164],
         [0.7399, 0.4139]]])


In [12]:
print(A.dim())

3


In [13]:
print(A.size())

torch.Size([3, 2, 2])


In [14]:
print(A.size(0))

3


In [15]:
print(A.size(1))

2


In [16]:
A=torch.rand(3,2,4)
print(A)

tensor([[[0.4393, 0.4719, 0.6495, 0.9957],
         [0.4500, 0.7124, 0.3126, 0.8423]],

        [[0.8719, 0.4880, 0.7594, 0.7086],
         [0.0406, 0.7802, 0.9614, 0.7100]],

        [[0.4435, 0.9687, 0.8397, 0.9858],
         [0.5354, 0.8347, 0.8801, 0.2005]]])


In [17]:
print(A.size(2))

4


A 2-dimensional Tensor

In [18]:
B=torch.rand(3,5)
print(B)

tensor([[0.2276, 0.9603, 0.0211, 0.0512, 0.8323],
        [0.4934, 0.9329, 0.6940, 0.0550, 0.9672],
        [0.2806, 0.3380, 0.6764, 0.3781, 0.6062]])


In [19]:
print(B.dim())

2


In [20]:
print(B.size())

torch.Size([3, 5])


In [21]:
print(B.size(0))

3


In [22]:
print(B.size(1))

5


A 1-dimensional Tensor

In [23]:
x=torch.rand(7)
print(x)

tensor([0.9025, 0.9193, 0.6086, 0.0465, 0.2989, 0.5076, 0.6191])


In [24]:
print(x.dim())

1


In [25]:
print(x.size())

torch.Size([7])


Adding and multiplying tensors

In [26]:
A=torch.rand(2,2)
B=torch.rand(2,2)

C=2*B
D=A+C
E=A*B

print(A)
print('')
print(B)
print('')
print(C)
print('')
print(C)
print('')
print(E)

tensor([[0.1049, 0.8155],
        [0.1294, 0.6255]])

tensor([[0.0153, 0.9378],
        [0.4890, 0.7759]])

tensor([[0.0305, 1.8755],
        [0.9780, 1.5517]])

tensor([[0.0305, 1.8755],
        [0.9780, 1.5517]])

tensor([[0.0016, 0.7648],
        [0.0633, 0.4853]])


Floats versus integers

In [27]:
x=torch.Tensor([1.2 , 2.5])
print(x)
print(x.type())

tensor([1.2000, 2.5000])
torch.FloatTensor


In [28]:
y=torch.LongTensor([5,6])
print(y)
print(y.type())

tensor([5, 6])
torch.LongTensor


In [29]:
y=y.float()
print(y)
print(y.type())

tensor([5., 6.])
torch.FloatTensor


In [30]:
x=x.long()
print(x)
print(x.type())

tensor([1, 2])
torch.LongTensor


Other function

In [31]:
x=torch.arange(10)
print(x)
print(x.type())

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.LongTensor


In [32]:
x=torch.randperm(10)
print(x)
print(x.type())

tensor([4, 1, 3, 8, 2, 0, 7, 5, 9, 6])
torch.LongTensor


In [33]:
x=torch.arange(10).long()
print(x)
print(x.type())

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.LongTensor


# Tips 
Check tensor sizes for algebra computations like multiplication torch.mm(X1,X2) with X1.size(), X2.size()

Check tensor type for data manipulations with X.type()

Reshaping a tensor

In [34]:
x=torch.arange(10)
print(x)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [35]:
print(x.view(2,5))

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


In [36]:
print(x.view(5,2))

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


Note that the original tensor x was NOT modified

In [37]:
print(x)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


To make the change permanent you need to create a new tensor

In [38]:
y=x.view(5,2)

print(x)
print('')
print(y)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


Slicing a tensor

In [39]:
print( y )

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [40]:
print(y[0])

tensor([0, 1])


In [41]:
print(y[1])

tensor([2, 3])


In [42]:
print(y[2])

tensor([4, 5])


Extract row 1 (included) to row 4 (excluded)

In [43]:
print(y)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [44]:
print(y[1:4])

tensor([[2, 3],
        [4, 5],
        [6, 7]])


Let check the sizes after slicing

In [45]:
print(y)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [46]:
z= y[1:1+3]
print(z)

print('')

print('dimension=',z.dim())
print(z.size())

tensor([[2, 3],
        [4, 5],
        [6, 7]])

dimension= 2
torch.Size([3, 2])


In [47]:
v=y[1]
print(v)

print('')


print('dimension=',v.dim())
print(v.size())

tensor([2, 3])

dimension= 1
torch.Size([2])


Acessing the entries of a Tensor

In [48]:
print(y)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [49]:
a=y[4,0]
print(a)

tensor(8)


In [50]:
print(a.dim())
print(a.size())

0
torch.Size([])


A matrix is 2-dimensional Tensor \\
A row of a matrix is a 1-dimensional Tensor \\ 
An entry of a matrix is a 0-dimensional  Tensor \\

0-dimensional Tensor are scalar! \\

If we want to convert a 0-dimensional Tensor into  python number, we need to use item()

In [51]:
b=a.item()
print(a)
print(type(a))
print(b)
print(type(b))

tensor(8)
<class 'torch.Tensor'>
8
<class 'int'>


Manipulate PyTorch Tensors

Make the matrices A and B below. Add them together to obtain a matrix C. Print these three matrices.
$$
A =\begin{bmatrix}
1 & 2 \\ 3 & 4
\end{bmatrix}  
\qquad 
B =\begin{bmatrix}
10 & 20 \\ 30 & 40
\end{bmatrix}  \qquad C=A+B =?
$$

In [52]:
A=torch.Tensor( [ [1,2] , [3,4] ] )
B=torch.Tensor( [ [10,20] , [30,40] ] )

C=A+B

print(A)
print('')
print(B)
print('')
print(C)

tensor([[1., 2.],
        [3., 4.]])

tensor([[10., 20.],
        [30., 40.]])

tensor([[11., 22.],
        [33., 44.]])


Print the sizes, dimension, and type of the matrix A. Remember, the commands are size(), dim() and type()

In [53]:
print(A.size())
print(A.dim())
print(A.type())

torch.Size([2, 2])
2
torch.FloatTensor


Convert the matrix A to be an integer matrix  (type LongTensor). Remember, the command is long(). Then print the type to check it was indeed converted

In [54]:
A=A.long()
print(A)
print(A.type())

tensor([[1, 2],
        [3, 4]])
torch.LongTensor


Make a random 5 x 2 x 3 Tensor. The command is torch.rand.  Then do the following: \\
1) Print the tensor \\
2) Print its type \\
3) Print its dimension \\
4) Print its size \\
5) Print the size of its middle dimension.

In [55]:
A=torch.rand(5,2,3)
print(A)
print(A.type())
print(A.dim())
print(A.size())
print(A.size(1))

tensor([[[0.9462, 0.1770, 0.7652],
         [0.0966, 0.4025, 0.7562]],

        [[0.8390, 0.2063, 0.3939],
         [0.7034, 0.6575, 0.1603]],

        [[0.0616, 0.4694, 0.7351],
         [0.8529, 0.7835, 0.9564]],

        [[0.6566, 0.3133, 0.8419],
         [0.6036, 0.5979, 0.2861]],

        [[0.9038, 0.9559, 0.0936],
         [0.0460, 0.3351, 0.8281]]])
torch.FloatTensor
3
torch.Size([5, 2, 3])
2


Make 2 x 3 x 4 x 5 tensor filled with zeros then print it. (The command is torch.zeros). See if you can make sense of the display

In [56]:
A=torch.zeros(2,3,4,5)
print(A)

tensor([[[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]]])


In [57]:
x=A[0,0]
print(x)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
